//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Odev6.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class doktor_table
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string bolum { get; set; }
        public string seviye { get; set; }
        public double tecrube { get; set; }
        public string kullaniciadi { get; set; }
        public string parola { get; set; }
    }
}
