//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Odev6.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Web_OdevEntities3 : DbContext
    {
        public Web_OdevEntities3()
            : base("name=Web_OdevEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<birimler_table> birimler_table { get; set; }
        public virtual DbSet<doktor_table> doktor_table { get; set; }
        public virtual DbSet<hasta_table> hasta_table { get; set; }
        public virtual DbSet<hastalik> hastalik { get; set; }
        public virtual DbSet<ilaclar_table> ilaclar_table { get; set; }
        public virtual DbSet<randevu_table> randevu_table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
